# Generated by Django 3.0.3 on 2020-04-16 14:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('candidates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Name'), size=None)),
                ('on_invitation_only', models.BooleanField(default=False)),
                ('num_grades', models.PositiveSmallIntegerField(verbose_name='Num. grades')),
                ('start_at', models.IntegerField(default=1587048322, verbose_name='Start date')),
                ('finish_at', models.IntegerField(default=1587048323, verbose_name='End date')),
                ('select_language', models.CharField(default='en', max_length=2, verbose_name='Language')),
                ('restrict_results', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades_by_candidate', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(verbose_name='Note'), size=None)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
