# Generated by Django 3.0.3 on 2020-04-28 10:52

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='finish_at',
            field=models.IntegerField(default=time.time, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='restrict_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_at',
            field=models.IntegerField(default=time.time, verbose_name='Start date'),
        ),
    ]
