# Generated by Django 3.0.3 on 2020-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='finish_at',
            field=models.IntegerField(default=1587059215, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='restrict_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_at',
            field=models.IntegerField(default=1587059214, verbose_name='Start date'),
        ),
    ]
