# Generated by Django 3.0.3 on 2020-05-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200428_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='email',
        ),
    ]
