# Generated by Django 3.0.3 on 2020-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200416_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='finish_at',
            field=models.IntegerField(default=1587400613, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_at',
            field=models.IntegerField(default=1587400612, verbose_name='Start date'),
        ),
    ]
