# Generated by Django 3.1.1 on 2021-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='send_mail',
            field=models.BooleanField(default=True),
        ),
    ]
