# Generated by Django 2.2.1 on 2019-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20190602_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='num_grades',
            field=models.SmallIntegerField(default=20, verbose_name='Num. grades'),
        ),
    ]
