# Generated by Django 2.2.1 on 2019-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20190610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='num_grades',
            field=models.PositiveSmallIntegerField(verbose_name='Num. grades'),
        ),
    ]
