# Generated by Django 2.2.1 on 2019-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20190610_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='is_started',
            field=models.BooleanField(default=True),
        ),
    ]
