# Generated by Django 2.2.5 on 2019-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20190912_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
