# Generated by Django 3.0.1 on 2020-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_election_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='selec_language',
            field=models.CharField(default='fr_FR', max_length=5, verbose_name='Language'),
        ),
    ]
