# Generated by Django 3.0.1 on 2020-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_election_selec_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='selec_language',
            field=models.CharField(default='fr', max_length=2, verbose_name='Language'),
        ),
    ]
