# Generated by Django 3.0.1 on 2020-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20200213_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='finished_at',
            field=models.IntegerField(default=1584958163, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='election',
            name='started_at',
            field=models.IntegerField(default=1584958162, verbose_name='Start date'),
        ),
    ]
