# Generated by Django 3.0.1 on 2020-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20200323_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='finished_at',
            field=models.IntegerField(default=1584958373, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='started_at',
            field=models.IntegerField(default=1584958372, verbose_name='Start date'),
        ),
    ]
