# Generated by Django 3.0.1 on 2020-04-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0017_auto_20200411_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='is_opened',
            new_name='restrict_results',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_started',
        ),
        migrations.AlterField(
            model_name='election',
            name='finish_at',
            field=models.IntegerField(default=1587037301, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_at',
            field=models.IntegerField(default=1587037300, verbose_name='Start date'),
        ),
    ]
