"""Add ballot table and ballot_id to votes

Revision ID: 81b4c6fc826d
Revises: 48bf0bdc1ca1
Create Date: 2025-10-31 17:07:55.504501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b4c6fc826d'
down_revision = '48bf0bdc1ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('voter_uuid', sa.UUID(), nullable=True),
        sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('election_ref', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['election_ref'], ['elections.ref'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballots_id'), 'ballots', ['id'], unique=False)
    op.create_index(op.f('ix_ballots_voter_uuid'), 'ballots', ['voter_uuid'], unique=True)
    op.add_column('votes', sa.Column('ballot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'ballots', ['ballot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'ballot_id')
    op.drop_index(op.f('ix_ballots_voter_uuid'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_id'), table_name='ballots')
    op.drop_table('ballots')
    # ### end Alembic commands ###
