name: test-driven development

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Static typing with mypy
        run: |
          # stop the build if there are MyPy errors
          mypy app --show-traceback
      - name: Test with pytest
        env: 
          SECRET: rmO8kBuJPGzuy7g
        run: |
          SQLITE=True pytest
